name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./reservation-backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw package -B

      - name: Run Integration Tests
        run: ./mvnw verify -B
